name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux (Swift 6.1)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container: swift:6.1-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

  macos:
    name: macOS (Xcode 16)
    runs-on: macos-14
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use the default Xcode on the runner (Xcode 16 on macOS-14)

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
